### ISSUE TITLE
An option to prevent ellipses obscuring important info

### ISSUE THREAD

**Issue by Joystick74** [personalmountains/CustomTabNames#12]
It would be nice if there was an option to switch off the ellipses so that as much of the (e.g.) filename was shown from the start.

For example, in a project where EVERY file is called PurchaseOrderEdit[Something Unique].component.ts it would be good to see PurchaseOrderEditSomet... rather than every tab being PurchaseOrd...mponent.ts

**Comment by personalmountains** [comment]
The ellipsis is controlled by VS during rendering, CTN really is just about setting the caption. I'm closing this as wontfix as it's out of scope.

Note that 2022 has an option to set the minimum tab width in Environment/Tabs and Windows, which might help. I'm also thinking about #13 right now, which could allow you to fix your particular use case.
